name: Sphinx build

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          ./scripts/install.sh
      - name: Test
        run: |
          ./scripts/test.sh
      - name: Sphinx build
        run: |
          ./scripts/build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true


      - name: Publish on Pypi
        run: |
          ./scripts/publish.sh ${{ secrets.PYPI_REPO }} ${{ secrets.PYPI_PASS }}